// scripts/process-music.mjs loads this file on its own, outside the Next
// build, to read slugs, titles and years for the MP3 tags. Keep every import
// here `import type` - a value import would break that script.
import type { CompositionEntry } from '@/types/music';

// To add a piece: save its score as music-src/{slug}.mscz, add an entry here
// with the same slug, and run `pnpm music`. See scripts/README.md.
export const COMPOSITIONS: CompositionEntry[] = [
  {
    slug: 'nice',
    title: 'Nice',
    subtitle: 'An original composition for my high school strings class',
    instrumentation: 'Viola, Cello',
    year: 2019,
    order: 1,
    featured: true,
    writeup: `Placeholder writeup.`,
  },
  {
    slug: 'arr-of-qingyun-peak-themes',
    title: 'Qingyun Peak Themes',
    subtitle: 'An arrangement from a game song',
    instrumentation: 'Flute, Violin, Cello',
    year: 2021,
    order: 2,
    featured: true,
    writeup: `Placeholder writeup.`,
  },
  {
    slug: 'bass-etude-no1-bass-riff',
    title: 'Bass Etude No. 1 "The Bass Riff"',
    subtitle: 'Groovy riff exploring silence',
    instrumentation: 'Electric Bass',
    year: 2020,
    order: 3,
    featured: false,
    writeup: `Placeholder writeup.`,
  },
  {
    slug: 'aboard-the-pirate-ship',
    title: 'Aboard the Pirate Ship',
    subtitle: '',
    instrumentation: 'Cello',
    year: 2020,
    order: 4,
    featured: false,
    writeup: `Placeholder writeup.`,
  },
  {
    slug: 'cello-miniature-a-happy-day',
    title: 'Cello Miniature "A Happy Day"',
    subtitle: 'for solo cello',
    instrumentation: 'Cello',
    year: 2021,
    order: 5,
    featured: false,
    writeup: `Placeholder writeup.`,
  },
  {
    slug: 'cello-miniature-no2-resonant',
    title: 'Cello Miniature No. 2 "Resonant"',
    subtitle: 'for solo cello',
    instrumentation: 'Cello',
    year: 2020,
    order: 6,
    featured: false,
    writeup: `Placeholder writeup.`,
  },
  {
    slug: 'fragment-for-solo-cello',
    title: 'Fragment',
    subtitle: 'for solo cello',
    instrumentation: 'Cello',
    year: 2021,
    order: 7,
    featured: false,
    writeup: `Placeholder writeup.`,
  },
  {
    slug: 'skipping',
    title: 'Skipping',
    subtitle: '',
    instrumentation: 'Flute, Alto Saxophone, Tuba',
    year: 2024,
    order: 8,
    featured: false,
    writeup: `Placeholder writeup.`,
  },
  {
    slug: 'a-brown-ballad',
    title: 'A Brown Ballad',
    subtitle: 'for flute',
    instrumentation: 'Flute',
    year: 2022,
    order: 9,
    featured: false,
    writeup: `Placeholder writeup.`,
  },
  {
    slug: 'santiago-the-alchemist',
    title: 'Santiago',
    subtitle: 'Inspired by The Alchemist',
    instrumentation: 'Harp, Tuba, Flute, Cello, Viola',
    year: 2020,
    order: 10,
    featured: false,
    writeup: `Placeholder writeup.`,
  },
  {
    slug: 'bass-riff-for-flute',
    title: 'Flute Etude No. 1 "The Bass Riff"',
    subtitle: 'A flute version of my bass riff',
    instrumentation: 'Treble Flute',
    year: 2022,
    order: 11,
    featured: false,
    writeup: `Placeholder writeup.`,
  },
  {
    slug: 'a-trumpets-promise-strings-aleotoric-composition',
    title: "A Trumpet's Promise",
    subtitle: 'An aleatoric composition from a class assignment',
    instrumentation: 'B♭ Trumpet',
    year: 2021,
    order: 12,
    featured: false,
    writeup: `Placeholder writeup.`,
  },
];
