/**
 * Slugs that have media: a poster at public/projects/{slug}.webp and a loop in
 * R2 at projects/{slug}.mp4. One list, because the poster is cut from the loop
 * — there is never one without the other.
 *
 * GENERATED by scripts/prepare-project-assets.sh from what's in
 * public/projects/. A slug that isn't here renders a skeleton in the card's
 * 16:9 slot.
 */
export const PROJECT_MEDIA: string[] = [
  'dino-mind',
  'finance-tracker',
  'flappy-bird',
  'hatch-booking-system',
  'infinity-chess',
  'island-builder',
  'job-application-tracker',
  'medisafe',
  'mes-website',
  'monpoke',
  'piraten-kapern',
];
